>>> Date-Time
>> Full Date-Time
--- gr
<2018-05-10 10:10>
---
--- html
<time datetime="2018-05-10 10:10">2018-05-10 10:10</time>
---

>> Partial Date-Time
--- gr
Diary <2018-05-10>

Met Sofia at <10:00> talked about her newborn child.
He said his first word today.
---
--- html
<p>Diary <time datetime="2018-05-10">2018-05-10</time></p>

<p>Met Sofia at <time datetime="10:00">10:00</time> talked about her newborn child.
He said his first word today.</p>
---
