>>> Todo

>> Bugs
[x] Nested definition list broken if the body starts with paragraph
	> OK
	--- gr
	A ::
		B ::
			B is B
	---
	> Not OK
	--- gr
	A ::
		A is A
		B ::
			B is B
	---

>> New Features
[ ] Merge Cells
	[ ] Merge Columns
		--- gr
		| A | B | C |
		|2>  D  | F |
		| G | H | I |
		---
	[ ] Merge Rows
		--- gr
		| A   | B | C |
		|2< D | E | F |
		|     | H | I |
		---
	[ ] Merge Rows and Columns
		--- gr
		| A  | B  | C |
		|2>2<  D  | F |
		|         | I |
		---
