----
zero
zero

zero
		two
	one
				four
zero
	one

	one
----
---
document 
  paragraph
    text zero
    space
    text zero
  paragraph
    text zero
    indent
      indent
        paragraph
          text two
      paragraph
        text one
        indent
          indent
            indent
              paragraph
                text four
    text zero
    indent
      paragraph
        text one
      paragraph
        text one
---
