---
-a
--b
---c

d-e
f--g
h---i

"don't judge a book by it's cover"
---
---
document 
  paragraph
    punct hyphen
    text a
    space
    punct enDash
    text b
    space
    punct emDash
    text c
  paragraph
    text d
    punct hyphen
    text e
    space
    text f
    punct enDash
    text g
    space
    text h
    punct emDash
    text i
  paragraph
    punct quoteOpen
    text don
    punct squoteClose
    text t judge a book by it
    punct squoteClose
    text s cover
    punct quoteClose
---
