----
<Note> Note
<Hint> Hint
<Important> Important
<Warning> Warning
<See also> See also
<Tip> Tip
----
---
1:1 document
  1:1-7 admon Note
    1:8-11 text "Note"
  2:1-7 admon Hint
    2:8-11 text "Hint"
  3:1-12 admon Important
    3:13-21 text "Important"
  4:1-10 admon Warning
    4:11-17 text "Warning"
  5:1-10 admon See also
    5:11-18 text "See also"
  6:1-6 admon Tip
    6:7-9 text "Tip"
---
