----
| Name | Chromosome | Age |
|:-----|:----------:|----:|
| Noor |     XY     |  22 |
| Dori |     XX     |  19 |
----
---
document 
  table left, center, right
    row header
      cell
        text  Name 
      cell
        text  Chromosome 
      cell
        text  Age 
    row content
      cell
        text  Noor 
      cell
        text      XY     
      cell
        text   22 
    row content
      cell
        text  Dori 
      cell
        text      XX     
      cell
        text   19 
---
