---- gr
[file]
[file>heading]
[>heading]
[https://www.org]

[file](label)
[file>heading](label)
[>heading](label)
[https://www.org](label)
----
---
document 
  paragraph
    link file 
    space
    link file >heading 
    space
    link >heading 
    space
    link https://www.org 
  paragraph
    link file label
    space
    link file >heading label
    space
    link >heading label
    space
    link https://www.org label
---
