----
![file]
![https://www.org/cat.png]

![file](label)
![https://www.org/cat.png](label)

![https://www.org/cat.png]
----
---
{"kind":"document","children":[{"kind":"paragraph","range":[0,0,1,25],"children":[{"kind":"view","resource":"file","range":[0,0,0,6]},{"kind":"space","range":[0,7,0,7]},{"kind":"view","resource":"https:\/\/www.org\/cat.png","range":[1,0,1,25]}]},{"kind":"paragraph","range":[3,0,4,32],"children":[{"kind":"view","resource":"file","label":"label","range":[3,0,3,13]},{"kind":"space","range":[3,14,3,14]},{"kind":"view","resource":"https:\/\/www.org\/cat.png","label":"label","range":[4,0,4,32]}]},{"kind":"view","resource":"https:\/\/www.org\/cat.png","range":[6,0,6,25]}]}
---
