----
^[Bird Is Real]

~~ & Bird Is Real
~~ title  = Bird is Real
~~ author = Government Agent
~~ year   = 2024
----
---
{"kind":"document","children":[{"kind":"paragraph","range":[0,0,0,14],"children":[{"kind":"footnote","desc":"Bird Is Real","range":[0,0,0,14]}]},{"kind":"reference","id":"Bird Is Real","infos":{"title":"Bird is Real","author":"Government Agent","year":"2024"},"range":[2,0,2,28]}]}
---
