----
&[bird is real]

(&) bird is real
	title  = Bird is Real
	author = Government Agent
	year   = 2024
----
---
{"kind":"document","children":[{"kind":"paragraph","range":[0,0,0,14],"children":[{"kind":"inText","id":"bird is real","range":[0,0,0,14]}]},{"kind":"reference","id":"bird is real","range":[2,0,2,2],"children":[{"kind":"referenceInfo","key":"title","range":[3,1,3,22],"children":[{"kind":"text","content":" Bird is Real","range":[3,9,3,21]}]},{"kind":"referenceInfo","key":"author","range":[4,1,4,26],"children":[{"kind":"text","content":" Government Agent","range":[4,9,4,25]}]},{"kind":"referenceInfo","key":"year","range":[5,1,6,0],"children":[{"kind":"text","content":" 2024","range":[5,9,5,13]}]}]}]}
---
