>>>-> Punctuation Mark

>>-> Quotation
Any single or double apostrophe will be converted into the correct left and right quotes.

---- gr
"Don't you dare!" He said calmly.
----

>>-> Hyphen, En Dash, Em Dash
Two hyphen will make en dash.
Three hyphen will make em dash.

---- gr
# Hyphen
A closed-door meetings

# En dash
I’ll schedule you from 4:30--5:00

# Em dash
Wait! I forgot to tell you---
----