>>> Heading

--- gr
>>> Chapter

>> Section

> Subsection
---

>> Heading Subtitle
If the subsection modifier is placed in the next line of any headings. It will be parsed as subtitle.

--- gr
>>> Chapter
> Chapter Subtitle

>> Section
> Section Subtitle

> Subsection
> Subsection Subtitle
---

>> Heading Link

--- gr
>>> Laminal Flow

See [>Laminal Flow]

If on another file [Chapter 1.gr>Laminal Flow]
---
