>>> Heading

--- gr
>>> Chapter

>> Section

> Subsection
---

>> Heading Subtitle
If the segment modifier placed after one line any headings. It will be parsed as subtitle.

--- gr
>>> Chapter
> Chapter Subtitle

>> Section
> Section Subtitle

> Subsection
> Subsection Subtitle
---

>> Heading ID 

--- gr
>>> Chapter 1 > chapter-one

See [>chapter-one](chapter 1)

If on another file [chapter-1.gr>chapter-one](chapter 1)
---
