>>> Style

--- gr
*Anything inside two asterisks will be rendered as bold font style.*
---
--- html
<p><b>Anything inside two asterisks will be rendered as bold font style.</b></p>
---

--- gr
_Anything inside two underscores will be rendered as italic font style._
---
--- html
<p><i>Anything inside two underscores will be rendered as italic font style.</i></p>
---

--- gr
Hello _*darkness* my old_ friend
---
--- html
<p>Hello <i><b>darkness</b> my old</i> friend</p>
---
