>>> Punctuation Mark

>> Quotation
Any single or double apostrophe will be converted into the correct left and right quotes.

--- gr
"Don't you dare!" He said calmly.
---

>> Minus, Hyphen, And En Dash
If the left side of minus is number it will became the number minus else hyphen
--- gr
-4 degree

A closed-door meetings
---

Two minus will make en dash.
--- gr
I'll schedule you from 4:30--5:00
---
