>>> Admonition
Avaliable levels are:
--- gr
</> Note
<?> Hint
<!> Important
<^> Warning
<&> See also
<+> Tip
---

>> One Line Admonition
--- gr
<!> Something here
---

>> Multi Line Admonition
--- gr
<!> Something here
	Every +1 indent after admonition modifier will be subcontent of this admonition.
---

--- gr-rule
admon = angleOpen (slash|quesMark|exclMark|caret|percent|amp) angleClose any newline
admonBody = admon (indent++)+
---
