>>> Linker

>> Net Link
--- gr
[http://google.com]
---

> With Label
--- gr
[http://google.com](Google)
---

>> Heading Link

--- gr
[>Laminal Flow]
---

> With Label
--- gr
[>Laminal Flow](see this segment)
---

>> Local Link

--- gr
[Another Document.gr]
---

> With Label
--- gr
[Another Document.gr](see this document)
---

> With Specified Heading
---
[Another Document.gr>Legal Section]
---

> With Specified Heading and Label
---
[Another Document.gr>Legal Section](see this section)
---
