:: code 'cxx'
---
#include <IO.hpp>

Model* LoadModel(const std::string& path) 
{
    unsigned char* bytes = IO::LoadBinary(path);

    Model* model = new Model::CreateFromBytes(bytes);

    model->SetParentContext(this);
    model->SetName("Untitled");

    return model;
}
---

    :: code 'shell'
    ---
    echo 'hello indent'
    ---

    :: code 'ruby'
    ---
    print 'hello indent'
    def shit()
        print 'not shit'
    end
prs
    ---


:: code 'gr'
-----
---
*CodeCeption*
---
-----
