> HEAD
Here thing you should do:
- First item
- Second item
- Third item
    Paragraph
    Still the same
    - List inside paragraph
    - What???
        - It's getting cooler
            - Than ever

    Different paragraph

- Forth item
1. One
2. Two
    .. Two A
    .. Two B
.. Three
.. Four

[ ] Buy milk
[-] Cry about the sad story
    [+] Vampire with blood intolerant
    [ ] Dog with few friends
[+] Clean dishes
