>>> Title

Paragraph

Another paragraph
    Indentation

- list
- list
- list

$ admonition 'important'
---
You cannot do this
---

$ table
---
1 | 2 | 3
---

$ code
---
Console.WriteLine("Hello World!");
---

~ file inclusions
$ file 'someFile.gr'
$ image 'someImage.png'

~ variable assignments
$ author = 'Noor Wachid'

~ internal meta-document
~ - print the table of contents created
$ toc

~ - print the index created by {?} function
$ index

~ - print the reference table you can refer them with {^} function
$ reference
---
book1 = [
    author = 'Someone Name',
    year = 1999,
]
book2 = [
    type = 'website',
    url = 'http://google.com',
]
---